// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package user

import (
	"errors"
	"fmt"
)

const (
	// IdentityGenderUnspecified is a IdentityGender of type Unspecified.
	IdentityGenderUnspecified IdentityGender = "GENDER_UNSPECIFIED"
	// IdentityGenderFemale is a IdentityGender of type Female.
	IdentityGenderFemale IdentityGender = "GENDER_FEMALE"
	// IdentityGenderMale is a IdentityGender of type Male.
	IdentityGenderMale IdentityGender = "GENDER_MALE"
	// IdentityGenderDiverse is a IdentityGender of type Diverse.
	IdentityGenderDiverse IdentityGender = "GENDER_DIVERSE"
)

var ErrInvalidIdentityGender = errors.New("not a valid IdentityGender")

// String implements the Stringer interface.
func (x IdentityGender) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x IdentityGender) IsValid() bool {
	_, err := ParseIdentityGender(string(x))
	return err == nil
}

var _IdentityGenderValue = map[string]IdentityGender{
	"GENDER_UNSPECIFIED": IdentityGenderUnspecified,
	"GENDER_FEMALE":      IdentityGenderFemale,
	"GENDER_MALE":        IdentityGenderMale,
	"GENDER_DIVERSE":     IdentityGenderDiverse,
}

// ParseIdentityGender attempts to convert a string to a IdentityGender.
func ParseIdentityGender(name string) (IdentityGender, error) {
	if x, ok := _IdentityGenderValue[name]; ok {
		return x, nil
	}
	return IdentityGender(""), fmt.Errorf("%s is %w", name, ErrInvalidIdentityGender)
}

// MarshalText implements the text marshaller method.
func (x IdentityGender) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *IdentityGender) UnmarshalText(text []byte) error {
	tmp, err := ParseIdentityGender(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *IdentityGender) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
