package user

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/cenkalti/backoff/v4"
	"github.com/google/uuid"
	"github.com/rs/zerolog"

	errs "github.com/ulbwa/medincident-command-service/internal/common/errors"
	"github.com/ulbwa/medincident-command-service/internal/common/outbox"
	"github.com/ulbwa/medincident-command-service/internal/common/persistence"
	"github.com/ulbwa/medincident-command-service/internal/model"
	"github.com/ulbwa/medincident-command-service/pkg/utils"
)

type Service struct {
	txFactory        persistence.TransactionFactory
	eventDispatcher  outbox.EventDispatcher
	identityProvider IdentityProvider
	repo             Repository
}

func NewService(txFactory persistence.TransactionFactory, eventDispatcher outbox.EventDispatcher, identityProvider IdentityProvider, repo Repository) (*Service, error) {
	if txFactory == nil {
		return nil, errors.New("transaction factory is required")
	}
	if eventDispatcher == nil {
		return nil, errors.New("event dispatcher is required")
	}
	if identityProvider == nil {
		return nil, errors.New("identity provider is required")
	}
	if repo == nil {
		return nil, errors.New("repository is required")
	}
	return &Service{
		txFactory:        txFactory,
		eventDispatcher:  eventDispatcher,
		identityProvider: identityProvider,
		repo:             repo,
	}, nil
}

func (s *Service) dispatchBackgroundIdentitySync(ctx context.Context, user *model.User, operation string) {
	bgCtx := context.WithoutCancel(ctx)
	go func() {
		syncCtx, cancel := context.WithTimeout(bgCtx, 2*time.Minute)
		defer cancel()

		if err := s.syncHumanIdentity(syncCtx, user); err != nil {
			zerolog.Ctx(syncCtx).Error().
				Err(err).
				Str("user_id", user.ID.String()).
				Str("operation", operation).
				Msg("background profile sync to identity service failed")
			return
		}

		zerolog.Ctx(syncCtx).Debug().
			Str("user_id", user.ID.String()).
			Str("operation", operation).
			Msg("successfully synced user profile to identity service in background")
	}()
}

// dispatchBackgroundUserMetadataUpdate asynchronously writes the application-level
// UserID back to the identity provider after the creation transaction commits.
// This is a best-effort operation: failures are logged but do not affect the caller.
// The UserCreatedEvent emitted to the outbox carries the same information, so a
// relay-based handler can serve as the durable delivery path once implemented.
func (s *Service) dispatchBackgroundUserMetadataUpdate(ctx context.Context, user *model.User) {
	bgCtx := context.WithoutCancel(ctx)
	go func() {
		updateCtx, cancel := context.WithTimeout(bgCtx, 2*time.Minute)
		defer cancel()

		userID := user.ID
		metadata := &IdentityUserMetadata{UserID: &userID}

		b := backoff.NewExponentialBackOff()
		err := backoff.Retry(func() error {
			return s.identityProvider.UpdateUserMetadata(updateCtx, user.IdentityID, metadata)
		}, backoff.WithContext(b, updateCtx))
		if err != nil {
			zerolog.Ctx(updateCtx).Error().
				Err(err).
				Str("user_id", user.ID.String()).
				Str("identity_id", user.IdentityID).
				Msg("background user metadata update to identity provider failed")
			return
		}

		zerolog.Ctx(updateCtx).Debug().
			Str("user_id", user.ID.String()).
			Str("identity_id", user.IdentityID).
			Msg("successfully updated user metadata in identity provider in background")
	}()
}

func (s *Service) syncHumanIdentity(ctx context.Context, user *model.User) error {
	identity, err := s.identityProvider.Get(ctx, user.IdentityID)
	if err != nil {
		return fmt.Errorf("failed to get identity for user %s: %w", user.ID.String(), err)
	}

	if identity.Human == nil {
		return fmt.Errorf("identity profile for user %s is not a human, cannot sync", user.ID.String())
	}

	preferredName := user.PreferredName()
	humanUpdate := &IdentityHuman{
		GivenName:         preferredName.GivenName,
		FamilyName:        preferredName.FamilyName,
		NickName:          utils.Ptr(preferredName.ShortName()),
		DisplayName:       preferredName.DisplayName(),
		Gender:            identity.Human.Gender,            // keep old
		PreferredLanguage: identity.Human.PreferredLanguage, // keep old
	}

	b := backoff.NewExponentialBackOff()

	operation := func() error {
		_, updateErr := s.identityProvider.UpdateHuman(ctx, user.IdentityID, humanUpdate)
		if updateErr != nil {
			return fmt.Errorf("update API call failed: %w", updateErr)
		}
		return nil
	}

	err = backoff.Retry(operation, backoff.WithContext(b, ctx))
	if err != nil {
		return fmt.Errorf("failed to sync profile to identity service after multiple attempts: %w", err)
	}

	return nil
}

type (
	// CreateUserRequest carries the identity provider ID and the user's name.
	// The application-level UserID (UUIDv7) is generated by the service itself.
	CreateUserRequest struct {
		IdentityID string
		GivenName  string
		FamilyName string
		MiddleName *string
	}

	CreateUserResponse struct {
		User *model.User
	}
)

func (s *Service) Create(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	if req == nil {
		return nil, errs.ErrInvalidRequest
	}

	identity, err := s.identityProvider.Get(ctx, req.IdentityID)
	if err != nil {
		if errors.Is(err, errs.ErrIdentityNotFound) {
			return nil, errs.ErrIdentityNotFound
		}
		return nil, fmt.Errorf("failed to get identity: %w", err)
	}

	if identity.Human == nil {
		return nil, errs.ErrIdentityNotHuman
	}

	if identity.Metadata != nil && identity.Metadata.UserID != nil {
		return nil, errs.ErrIdentityAlreadyLinked
	}

	userID, err := uuid.NewV7()
	if err != nil {
		return nil, fmt.Errorf("failed to generate user ID: %w", err)
	}

	userName, err := model.NewUserName(req.GivenName, req.FamilyName, req.MiddleName)
	if err != nil {
		return nil, err
	}

	var createdUser *model.User

	txCtx, tx, err := s.txFactory.Begin(ctx)
	if err != nil {
		return nil, fmt.Errorf("failed to begin transaction: %w", err)
	}

	err = persistence.WithinTransaction(txCtx, tx, func() error {
		alreadyExists, err := s.repo.ExistsByIdentityID(txCtx, req.IdentityID)
		if err != nil {
			return err
		}
		if alreadyExists {
			return errs.ErrUserAlreadyExists
		}

		user, err := model.NewUser(userID, req.IdentityID, userName)
		if err != nil {
			return err
		}

		if err := s.repo.Save(txCtx, user); err != nil {
			return fmt.Errorf("failed to save user: %w", err)
		}

		if err := s.eventDispatcher.Dispatch(txCtx, tx, user); err != nil {
			return fmt.Errorf("failed to dispatch domain events: %w", err)
		}

		createdUser = user
		return nil
	})
	if err != nil {
		return nil, err
	}

	// Write the application UserID back to the IdP after the transaction commits.
	// The UserCreatedEvent in the outbox provides a durable delivery path for when
	// a relay handler is implemented.
	s.dispatchBackgroundUserMetadataUpdate(ctx, createdUser)
	s.dispatchBackgroundIdentitySync(ctx, createdUser, "create user")

	return &CreateUserResponse{
		User: createdUser,
	}, nil
}

type OverrideUserNameRequest struct {
	UserID     uuid.UUID
	GivenName  string
	FamilyName string
	MiddleName *string
}

func (s *Service) OverrideName(ctx context.Context, req *OverrideUserNameRequest) error {
	if req == nil {
		return errs.ErrInvalidRequest
	}

	customName, err := model.NewUserName(req.GivenName, req.FamilyName, req.MiddleName)
	if err != nil {
		return err
	}

	var updatedUser *model.User

	txCtx, tx, err := s.txFactory.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}

	err = persistence.WithinTransaction(txCtx, tx, func() error {
		user, err := s.repo.GetByID(txCtx, req.UserID)
		if err != nil {
			return fmt.Errorf("failed to get user: %w", err)
		}

		if err := user.OverrideName(customName); err != nil {
			return err
		}

		if err := s.repo.Save(txCtx, user); err != nil {
			return fmt.Errorf("failed to save user: %w", err)
		}

		if err := s.eventDispatcher.Dispatch(txCtx, tx, user); err != nil {
			return fmt.Errorf("failed to dispatch domain events: %w", err)
		}

		updatedUser = user
		return nil
	})
	if err != nil {
		return err
	}

	s.dispatchBackgroundIdentitySync(ctx, updatedUser, "override name")

	return nil
}

type ClearCustomNameRequest struct {
	UserID uuid.UUID
}

// ClearCustomName resets user's custom name matching business invariant logic
func (s *Service) ClearCustomName(ctx context.Context, req *ClearCustomNameRequest) error {
	if req == nil {
		return errs.ErrInvalidRequest
	}

	var syncedUser *model.User

	txCtx, tx, err := s.txFactory.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}

	err = persistence.WithinTransaction(txCtx, tx, func() error {
		u, err := s.repo.GetByID(txCtx, req.UserID)
		if err != nil {
			return fmt.Errorf("failed to get user: %w", err)
		}

		u.RemoveCustomName()

		if err := s.repo.Save(txCtx, u); err != nil {
			return fmt.Errorf("failed to save user: %w", err)
		}

		if err := s.eventDispatcher.Dispatch(txCtx, tx, u); err != nil {
			return fmt.Errorf("failed to dispatch domain events: %w", err)
		}

		syncedUser = u
		return nil
	})
	if err != nil {
		return err
	}

	s.dispatchBackgroundIdentitySync(ctx, syncedUser, "clear custom name")

	return nil
}

type GrantAdminRoleRequest struct {
	ActorID      uuid.UUID
	TargetUserID uuid.UUID
}

//nolint:dupl // Explicit separate use-case flow for readability and bounded-context clarity.
func (s *Service) GrantAdminRole(ctx context.Context, req *GrantAdminRoleRequest) error {
	if req == nil {
		return errs.ErrInvalidRequest
	}

	txCtx, tx, err := s.txFactory.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}

	err = persistence.WithinTransaction(txCtx, tx, func() error {
		// Load actor and check permissions first.
		actor, err := s.repo.GetByID(txCtx, req.ActorID)
		if err != nil {
			return fmt.Errorf("failed to get actor: %w", err)
		}
		if err := actor.CanManageAdminRole(); err != nil {
			return err
		}

		// Load target and apply use-case.
		user, err := s.repo.GetByID(txCtx, req.TargetUserID)
		if err != nil {
			return fmt.Errorf("failed to get user: %w", err)
		}
		if err := user.GrantAdminRole(actor); err != nil {
			return err
		}

		if err := s.repo.Save(txCtx, user); err != nil {
			return fmt.Errorf("failed to save user: %w", err)
		}

		if err := s.eventDispatcher.Dispatch(txCtx, tx, user); err != nil {
			return fmt.Errorf("failed to dispatch domain events: %w", err)
		}

		return nil
	})
	if err != nil {
		return err
	}

	return nil
}

type RevokeAdminRoleRequest struct {
	ActorID      uuid.UUID
	TargetUserID uuid.UUID
}

//nolint:dupl // Explicit separate use-case flow for readability and bounded-context clarity.
func (s *Service) RevokeAdminRole(ctx context.Context, req *RevokeAdminRoleRequest) error {
	if req == nil {
		return errs.ErrInvalidRequest
	}

	txCtx, tx, err := s.txFactory.Begin(ctx)
	if err != nil {
		return fmt.Errorf("failed to begin transaction: %w", err)
	}

	err = persistence.WithinTransaction(txCtx, tx, func() error {
		// Load actor and check permissions first.
		actor, err := s.repo.GetByID(txCtx, req.ActorID)
		if err != nil {
			return fmt.Errorf("failed to get actor: %w", err)
		}
		if err := actor.CanManageAdminRole(); err != nil {
			return err
		}

		// Load target and apply use-case.
		user, err := s.repo.GetByID(txCtx, req.TargetUserID)
		if err != nil {
			return fmt.Errorf("failed to get user: %w", err)
		}
		if err := user.RevokeAdminRole(actor); err != nil {
			return err
		}

		if err := s.repo.Save(txCtx, user); err != nil {
			return fmt.Errorf("failed to save user: %w", err)
		}

		if err := s.eventDispatcher.Dispatch(txCtx, tx, user); err != nil {
			return fmt.Errorf("failed to dispatch domain events: %w", err)
		}

		return nil
	})
	if err != nil {
		return err
	}

	return nil
}
