// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package identity

import (
	"errors"
	"fmt"
)

const (
	// GenderUnspecified is a Gender of type Unspecified.
	GenderUnspecified Gender = "GENDER_UNSPECIFIED"
	// GenderFemale is a Gender of type Female.
	GenderFemale Gender = "GENDER_FEMALE"
	// GenderMale is a Gender of type Male.
	GenderMale Gender = "GENDER_MALE"
	// GenderDiverse is a Gender of type Diverse.
	GenderDiverse Gender = "GENDER_DIVERSE"
)

var ErrInvalidGender = errors.New("not a valid Gender")

// String implements the Stringer interface.
func (x Gender) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x Gender) IsValid() bool {
	_, err := ParseGender(string(x))
	return err == nil
}

var _GenderValue = map[string]Gender{
	"GENDER_UNSPECIFIED": GenderUnspecified,
	"GENDER_FEMALE":      GenderFemale,
	"GENDER_MALE":        GenderMale,
	"GENDER_DIVERSE":     GenderDiverse,
}

// ParseGender attempts to convert a string to a Gender.
func ParseGender(name string) (Gender, error) {
	if x, ok := _GenderValue[name]; ok {
		return x, nil
	}
	return Gender(""), fmt.Errorf("%s is %w", name, ErrInvalidGender)
}

// MarshalText implements the text marshaller method.
func (x Gender) MarshalText() ([]byte, error) {
	return []byte(string(x)), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *Gender) UnmarshalText(text []byte) error {
	tmp, err := ParseGender(string(text))
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// AppendText appends the textual representation of itself to the end of b
// (allocating a larger slice if necessary) and returns the updated slice.
//
// Implementations must not retain b, nor mutate any bytes within b[:len(b)].
func (x *Gender) AppendText(b []byte) ([]byte, error) {
	return append(b, x.String()...), nil
}
